# Generated by Django 5.2.11 on 2026-04-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('ph', models.FloatField()),
                ('suggested_crops', models.TextField()),
                ('is_suitable', models.BooleanField()),
                ('seed_recommendation', models.TextField(blank=True, null=True)),
                ('sowing_window', models.TextField(blank=True, null=True)),
                ('fertilizer_recommendation', models.TextField(blank=True, null=True)),
                ('irrigation_schedule', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
