# Generated by Django 5.2.11 on 2026-04-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_predictionresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='nitrogen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='phosphorus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='potassium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='rainfall',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
